### ISSUE TITLE
As a user I want to create my user account using REST API invocation, so that I can create content in the platform

### ISSUE THREAD

**Issue by chathugaj** [chathugaj/td-api#13]
EPIC: #8 

As a user I want to create my user account using REST API invocation, so that I can create content in the platform

** Acceptance Criteria**

- [x] - User created in the system
- [x] - User profile is created in the system associted with the user

**Tasks**

- [x] - Implement user profile endpoint to get a list of profiles
- [x] - Implement user profile endpoint to get a specific profile by id
- [x] - Implement user profile endpoint to update a profile by id
- [x] - Implement security policy so that only the owner can update his own profile
