### ISSUE TITLE
As a developer I want to manaege comments through the REST API

### ISSUE THREAD

**Issue by chathugaj** [chathugaj/td-api#15]
EPIC: #10 

As a developer I want to manaege comments through the REST API

** Acceptance Criteria**

- [ ] - Comments created in the system associated with the post and the user
- [ ] - 404 for bad content
- [ ] - 403 for invalid payload
- [ ] - View list of all the comments 
- [ ] - View comment by id

**Tasks**

- [ ] - Implement comments endpoint to get a list of comments
- [ ] - Implement comments endpoint to create a comment
- [ ] - Implement comments endpoint to get a specific comment by id
- [ ] - Implement comments endpoint to update a comment by id
- [ ] - Implement security policy so that only the owner can update / delete his own profile 
- [ ] - Validate the comments payload 
- [ ] - Implement the API endpoints to add and remove like for a post

**Comment by chathugaj** [comment]
Duplicate #28
