### ISSUE TITLE
As a developer I have to setup my project, so that I can continue developing features

### ISSUE THREAD

**Issue by chathugaj** [chathugaj/td-api#2]

**Comment by chathugaj** [comment]
EPIC: #14 

Initial project setup: As a developer I have to setup my project, so that I can continue developing features

**Acceptance Criteria**

- [ ] Project runs locally without any issues
- [ ] All the dependencies are managed properly

**Tasks**
- [ ] Configure the project to run locally
- [ ] Manage dependencies
