### ISSUE TITLE
As a developer I want to manage posts through REST API, so that I can provide a rest API to the Web application

### ISSUE THREAD

**Issue by chathugaj** [chathugaj/td-api#27]
EPIC: <epic>

As a developer I want to manage posts through REST API, so that I can provide a rest API to the Web application

** Acceptance Criteria**

- [x] - Post created in the system
- [x] - 404 if a post is not found
- [x] - 403 i fobiden respons is sent pack
- [x] - View list of posts
- [x] - View a post with specific id

**Tasks**

- [x] - Implent the post endpoints to creae
- [x] - Implement the post endpoint to list all the posts
- [x] - Impleemnt the get operations 
- [x] -Validate the payload and return relevant response through
