### ISSUE TITLE
As a developer I want to manage likes to posts through the REST API

### ISSUE THREAD

**Issue by chathugaj** [chathugaj/td-api#28]
EPIC: #10 

As a developer I want to manage comments through the REST API

** Acceptance Criteria**

- [x] - Likes created in the system associated with the post and the user
- [x] - 403 for unauthorised access 
- [x] - View list of all the likes for the user
- [x] - Get the like for a post and for a particular user

**Tasks**

- [x] - Implement likes endpoint to get the like for a post of a currently logged in user
- [x] - Implement endpoint to delete a like from the system if user deselects the like
- [x] - Implement endpoint to get all likes for a particular user
- [x] - Implement security policy so that only the owner can add / remove a like to a post 
- [x] - Validate the likes
