### ISSUE TITLE
As a developer I want users to use the obtained token when invoking API endpoints, so that the API will know the user is authenticated 

### ISSUE THREAD

**Issue by chathugaj** [chathugaj/td-api#31]
EPIC: #12 

As a developer I want users to use the obtained token when invoking API endpoints, so that the API will know the user is authenticated 

** Acceptance Criteria**

- [x] - Token must be valid
- [x] - Token expires a new token should be obtained

**Tasks**

- [x] - Implement the token validation on the API endpoints
